"""New Migration

Revision ID: 34da71fd7609
Revises: 
Create Date: 2023-03-21 19:26:54.551623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34da71fd7609'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nasabah',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nama', sa.String(), nullable=True),
    sa.Column('nik', sa.String(), nullable=True),
    sa.Column('no_hp', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nasabah_id'), 'nasabah', ['id'], unique=False)
    op.create_table('rekening',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('no_rekening', sa.String(), nullable=True),
    sa.Column('saldo', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nasabah', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['nasabah'], ['nasabah.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaksi',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kode_transaksi', sa.String(), nullable=True),
    sa.Column('nominal', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('rekening', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['rekening'], ['rekening.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaksi')
    op.drop_table('rekening')
    op.drop_index(op.f('ix_nasabah_id'), table_name='nasabah')
    op.drop_table('nasabah')
    # ### end Alembic commands ###
