"""new migration

Revision ID: d3749cec3bf2
Revises: 34da71fd7609
Create Date: 2023-03-22 03:51:09.207288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3749cec3bf2'
down_revision = '34da71fd7609'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
